name: VelocityTeleporter
version: 1.1
main: io.github.bigcookie233.velocityteleporter.VelocityTeleporter
author: BigCookie233
commands:
  velocityteleporter:
    description: VelocityTeleporter
    usage: /velocityteleporter <server> <player>
    permission: velocityteleporter.command.velocityteleporter
    aliases: vt