name: XSender
version: 1.2
main: io.github.bigcookie233.xsender.XSender
author: BigCookie233
commands:
  velocityteleporter:
    description: XSender
    usage: /xsender <server> <player>
    permission: xsender.command.xsender
    aliases: xs